pipeline {
    agent any

    environment { 
        GITHUB_SECRET = credentials('github-2') 
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'parallel'
            }
        }
        stage('Test2') {
            steps {
                echo 'parallel'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        success {
            echo 'success'
            sh env
        }
        failure {
            echo 'failure'
        }
    }
}
