pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'parallel'
            }
        }
        stage('Test2') {
            steps {
                echo 'parallel'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    post {
        environment { 
            GITHUB_SECRET = credentials('github-2') 
        }
        success {
            echo 'success'
        }
        failure {
            echo 'failure'
        }
    }
}
